### ISSUE TITLE
Debug logging

### ISSUE THREAD

**Issue by riomus** [stevelacy/go-sentry-kubernetes#2]
Would it be possible to add some debug logging possibility? I have created a container that is always failing (kubectl run failure --image ubuntu --command asdasda) but I am not getting any sentry issues. Without any logging possibility (it is possible in python version) it is hard to debug what is happening.

**Comment by stephenlacy** [comment]
I'll add that thanks

**Comment by riomus** [comment]
That is awesome. Thank you.

**Comment by stephenlacy** [comment]
I added debug logging with `--debug` let me know if it is reporting

**Comment by riomus** [comment]
```
 ContainerCannotRun   - failure-85bb85cf6d-gdfjs
reporting:  ContainerCannotRun  
 ContainerCannotRun   - failure-85bb85cf6d-gdfjs
reporting:  ContainerCannotRun  
 ContainerCannotRun   - failure-85bb85cf6d-gdfjs
reporting:  ContainerCannotRun  
```
I can see that events are captured, also i can see that DSN is correct. Unfortunately i can not see any events in sentry. Is it possible to somehow check what is the result of event reporting to sentry?

**Comment by stephenlacy** [comment]
interesting, I am getting similar results on a test env.
The output of https://github.com/stevelacy/go-sentry-kubernetes/blob/master/sentry-kubernetes.go#L85 is just a hash of the sent message. It _appears_ to be working perfectly, but I am also not seeing anything in sentry.

I'll investigate farther.

**Comment by riomus** [comment]
I think that I have found the problem. You are creating a new raven client (https://github.com/stevelacy/go-sentry-kubernetes/blob/master/sentry-kubernetes.go#L34) while in reporting function you are using a global client (https://github.com/stevelacy/go-sentry-kubernetes/blob/master/sentry-kubernetes.go#L107) 
So instead of raven in line 107, use client (that you get as parameter)

**Comment by stephenlacy** [comment]
Oh, right... that was dumb, fixing

**Comment by stephenlacy** [comment]
Works now! 
<img width="318" alt="screen shot 2019-03-01 at 09 56 57" src="https://user-images.githubusercontent.com/5648999/53653359-5e3d6e80-3c08-11e9-83af-62728e0cfd64.png">
docker image `stevelacy/go-sentry-kubernetes:30eb13c` or `:latest` will have the changes

**Comment by riomus** [comment]
I can confirm that is working also for me.

**Comment by stephenlacy** [comment]
Sounds good, I'll be improving the error messages and scope of coverage soon
