### ISSUE TITLE
More meaningful error messages

### ISSUE THREAD

**Issue by riomus** [stevelacy/go-sentry-kubernetes#3]
Is it possible to provide more meaningful messages? Currently on any error i only get "Error <container name>" messages for example "Error Error - db-0"

**Comment by stephenlacy** [comment]
The error message is either directly from the Pod status, or would be constructed from one of the Pod's container state statuses. We could create an error title and details by getting the metrics from the pods as well as any container logs (if the logs are passed with kubernetes)

I don't really like the current messages, if you want to send a PR I'd appreciate it, if not I'll get around to it.

**Comment by riomus** [comment]
I would love to help with that, but GO is quite new for me, and it might take me some time to find out how to do it properly.

**Comment by wichert** [comment]
I just got this as well. The error is indeed not very informative:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/199657/67267846-6dcd3880-f4b3-11e9-95e7-25c512cf4909.png">

However the tags are more informative, in particular the `message` tag:

<img width="824" alt="image" src="https://user-images.githubusercontent.com/199657/67267871-7a519100-f4b3-11e9-955f-dde6344039e4.png">

Perhaps that should be used for the report title?

**Comment by wichert** [comment]
What would probably be extremely useful is collecting the recent events for the resource, and adding those as breadcrumbs to the report.

**Comment by wichert** [comment]
Interestingly the official sentry kubernetes client seems to do exactly that: instead of monitoring pods it watches all events and sends warning and error events to sentry.

**Comment by stephenlacy** [comment]
@wichert would you be interested in adding your reporter function to this project? Since you already created it, I would want you to get the credit for the code commit.

**Comment by wichert** [comment]
I'm not entirely it makes sense to add my reporter here. Your approach is based on watching changes to pods, while I'm watching for events to be created. I'm not sure it makes sense to have both approaches in a single tool.

**Comment by stephenlacy** [comment]
@riomus finally got around to it on a flight, the error reported should look something like this:
<img width="685" alt="Screen Shot 2019-10-30 at 17 14 12" src="https://user-images.githubusercontent.com/5648999/67908436-c1392980-fb38-11e9-8dec-96b4274d59db.png">
Let me know what else you want added

**Comment by riomus** [comment]
@stevelacy  now it looks awesome and provides all required informations. I think that we could create a separate issue for events observing in order to send all waring/error events to sentry also.  Currently, only by pod observation, you will not get an error for example on image pull problem. What do you think about that?

**Comment by stephenlacy** [comment]
@riomus Sounds good

**Comment by wichert** [comment]
@riomus For what it's worth [k8s-sentry](https://github.com/wichert/k8s-sentry) already implements that. Feel free to to reuse code from there.

**Comment by riomus** [comment]
@wichert so if there is a better tool, then @stevelacy maybe you could mention it in the readme. There is no point in copy-pasting the code. You can always use both of them or just k8s-sentry (it does a superset of go-sentry-kubernetes features from what I see)
